import { createContext, useContext, useEffect, useState } from 'react';
import { Link, Navigate, NavLink, Outlet, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { ArrowRight, BookOpen, Compass, FileText, HeartHandshake, LayoutDashboard, LogOut, Menu, MessageCircle, ShieldCheck, Sparkles, UserRound, X } from 'lucide-react';
import { api, clearSession, hasSession, restoreSession, setSession } from './api';
import { ErrorNotice, Spinner } from './ui';
import { Dashboard, Profile, Recommendations } from './Citizen';
import { Catalog, SchemeDetail } from './Schemes';
import { Documents } from './Documents';
import { Chat } from './Chat';
import { Admin } from './Admin';

export const AuthContext = createContext(null);
export function useAuth() { return useContext(AuthContext); }
export default function App() {
  const [user, setUser] = useState(null), [loading, setLoading] = useState(hasSession);
  useEffect(() => { let active = true; if (hasSession()) restoreSession().then(async data => { const current = data.user || await api('/auth/me'); if (active) setUser(current); }).catch(() => { clearSession(); }).finally(() => { if (active) setLoading(false); });
    const expire = () => setUser(null); window.addEventListener('session-expired', expire); return () => { active = false; window.removeEventListener('session-expired', expire); }; }, []);
  async function signIn(payload) { setSession(payload); setUser(payload.user || await api('/auth/me')); }
  async function logout() { await api('/auth/logout', { method: 'POST' }); clearSession(); setUser(null); }
  if (loading) return <div className="boot"><Spinner label="Restoring your secure session…"/></div>;
  return <AuthContext.Provider value={{ user, signIn, logout }}><Routes><Route path="/login" element={user ? <Navigate to="/" replace/> : <AuthPage/>}/><Route path="/register" element={user ? <Navigate to="/" replace/> : <AuthPage register/>}/><Route element={user ? <Layout/> : <Navigate to="/login" replace/>}><Route index element={<Dashboard/>}/><Route path="profile" element={<Profile/>}/><Route path="schemes" element={<Catalog/>}/><Route path="schemes/:id" element={<SchemeDetail/>}/><Route path="recommendations" element={<Recommendations/>}/><Route path="documents" element={<Documents/>}/><Route path="chat" element={<Chat/>}/><Route path="admin" element={user?.role === 'admin' ? <Admin/> : <Forbidden/>}/><Route path="*" element={<Missing/>}/></Route></Routes></AuthContext.Provider>;
}
export function AuthPage({ register = false }) {
  const { signIn } = useAuth(); const navigate = useNavigate();
  const [form, setForm] = useState({ username: '', email: '', password: '' }), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  async function submit(e) { e.preventDefault(); setBusy(true); setError(''); try { let data = await api(`/auth/${register ? 'register' : 'login'}`, { method: 'POST', body: register ? form : { username: form.username, password: form.password } }); if (!data.access_token) data = await api('/auth/login', { method: 'POST', body: { username: form.username, password: form.password } }); await signIn(data); navigate('/'); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  return <main className="auth-screen"><section className="auth-story"><Link to="/" className="brand"><span className="brand-icon"><HeartHandshake size={28}/></span><span>Sahaay<span className="brand-sub">A LITTLE GUIDANCE. A STEP FORWARD.</span></span></Link><div><span className="eyebrow light">WELFARE, MADE UNDERSTANDABLE</span><h1>A clearer path to<br/><em>the support you need.</em></h1><p>Explore schemes, understand your eligibility, and put your documents in order — one step at a time.</p><div className="story-features"><span><Compass/>Discover relevant schemes</span><span><ShieldCheck/>Understand every requirement</span><span><FileText/>Prepare with confidence</span></div></div><p className="story-footer">Academic prototype · Synthetic demo data only<br/>Guidance does not establish official entitlement or submit applications.</p></section><section className="auth-panel"><div className="auth-form"><span className="eyebrow">YOUR NEXT STEP STARTS HERE</span><h2>{register ? 'Create your account' : 'Welcome back.'}</h2><p className="muted">{register ? 'Start with a few details. Your profile can grow later.' : 'Sign in to continue preparing for the support that matters.'}</p><ErrorNotice error={error}/><form onSubmit={submit}><label>Username<input autoComplete="username" required minLength={3} maxLength={50} value={form.username} onChange={e => setForm({ ...form, username: e.target.value })}/></label>{register && <label>Email address<input type="email" autoComplete="email" required value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/></label>}<label>Password<input aria-label="Password" type="password" autoComplete={register ? 'new-password' : 'current-password'} required minLength={register ? 10 : undefined} maxLength={128} value={form.password} onChange={e => setForm({ ...form, password: e.target.value })}/>{register && <small>Use at least 10 characters.</small>}</label><button className="button full" disabled={busy}>{busy ? 'Please wait…' : register ? 'Create account' : 'Sign in'}<ArrowRight size={18}/></button></form><p className="auth-switch">{register ? 'Already have an account?' : 'New to Sahaay?'} <Link to={register ? '/login' : '/register'}>{register ? 'Sign in' : 'Create an account'}</Link></p><div className="privacy-note"><ShieldCheck size={20}/><p>Use synthetic information for this demo. Your documents and conversations are private to your account.</p></div></div></section></main>;
}
function Layout() {
  const { user, logout } = useAuth(); const [open, setOpen] = useState(false), [error, setError] = useState(''); const location = useLocation();
  useEffect(() => { setOpen(false); }, [location.pathname]);
  const nav = [['/', LayoutDashboard, 'Overview'], ['/schemes', Compass, 'Explore schemes'], ['/recommendations', Sparkles, 'For you'], ['/profile', UserRound, 'My profile'], ['/documents', FileText, 'My documents'], ['/chat', MessageCircle, 'Ask Sahaay']];
  return <div className="app-shell"><a className="skip-link" href="#main">Skip to content</a><button className="mobile-menu" onClick={() => setOpen(!open)} aria-label={open ? 'Close menu' : 'Open menu'}>{open ? <X/> : <Menu/>}</button>{open && <button className="nav-backdrop" aria-label="Close menu" onClick={() => setOpen(false)}/>}<aside className={`sidebar ${open ? 'is-open' : ''}`}><Link to="/" className="brand"><span className="brand-icon"><HeartHandshake size={26}/></span><span>Sahaay<span className="brand-sub">WELFARE COMPANION</span></span></Link><div className="nav-label">YOUR SPACE</div><nav aria-label="Main navigation">{nav.map(([path, Icon, label]) => <NavLink end={path === '/'} key={path} to={path}><Icon size={19}/>{label}</NavLink>)}{user.role === 'admin' && <NavLink to="/admin"><ShieldCheck size={19}/>Administration</NavLink>}</nav><div className="sidebar-help"><BookOpen size={21}/><strong>A little clarity helps.</strong><p>Ask about benefits, requirements, or your next step.</p><Link to="/chat">Start a conversation <ArrowRight size={14}/></Link></div><div className="user-box"><div className="avatar">{user.username?.[0]?.toUpperCase() || 'U'}</div><div><strong>{user.username}</strong><span>{user.role === 'admin' ? 'Administrator' : 'Personal account'}</span></div><button className="icon-button" aria-label="Sign out" onClick={() => logout().catch(e => setError(e.message))}><LogOut size={19}/></button></div></aside><div className="main-shell"><div className="topbar"><span><span className="status-dot"/> Your personal welfare workspace</span><span className="prototype-pill">ACADEMIC PROTOTYPE</span></div><main id="main" tabIndex={-1}><ErrorNotice error={error}/><Outlet/></main><footer className="app-footer"><span>Sahaay · Helping you take an informed next step.</span><span>Guidance only. Scheme approval belongs to the issuing authority.</span></footer></div></div>;
}
function Forbidden() { return <section className="empty"><h1>Administrator access required</h1><p>Your account cannot access scheme management.</p><Link className="button" to="/">Return to overview</Link></section>; }
function Missing() { return <section className="empty"><h1>Page not found</h1><Link className="button" to="/">Return to overview</Link></section>; }

